# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
notifications:
  email:
    on_failure: always

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'


env:
  - FBI_API_KEY = "dw3MIpdbpWC8AyD5naDpjXZaEgFenyiGh3y0JP1a"
