ucr_arrest_offenses <- c("aggravated-assault",
                         "all-other-offenses",
                         "arson",
                         "burglary",
                         "curfew",
                         "disorderly-conduct",
                         "dui",
                         "drug-grand-total",
                         "drug-possession-marijuana",
                         "drug-possession-opium",
                         "drug-possession-other",
                         "drug-possession-subtotal",
                         "drug-possession-synthetic",
                         "drug-sales-marijuana",
                         "drug-sales-opium",
                         "drug-sales-other",
                         "drug-sales-subtotal",
                         "drug-sales-synthetic",
                         "drunkenness",
                         "embezzlement",
                         "forgery",
                         "fraud",
                         "gambling-all-other",
                         "gambling-bookmaking",
                         "gambling-numbers",
                         "gambling-total",
                         "human-trafficking-commercial",
                         "human-trafficking-servitude",
                         "larceny",
                         "liqour-laws", # MISPELLED
                         "motor-vehcile-theft", # MISPELLED
                         "murder",
                         "offense-against-family",
                         "prostitution",
                         "prostitution-assisting",
                         "prostitution-prostitution",
                         "prostitution-purchasing",
                         "rape",
                         "robbery",
                         "runaway",
                         "sex-offenses",
                         "simple-assault",
                         "stolen-property",
                         "suspicion",
                         "vagrancy",
                         "vandalism",
                         "weapons")

ucr_arrest_types <- c("male",
                      "female",
                      "race")


nibrs_offenses <- c("aggravated-assault",
                    "all-offenses",
                    "all-other-larceny",
                    "all-other-offenses",
                    "animal-cruelty",
                    "arson",
                    "assault-offenses",
                    "assisting-or-promoting-prostitution",
                    "bad-checks",
                    "betting",
                    "bribery",
                    "burglary-breaking-and-entering",
                    "counterfeiting-forgery",
                    "credit-card-automated-teller-machine-fraud",
                    "crime-against-person",
                    "crime-against-property",
                    "crime-against-society",
                    "curfew-loitering-vagrancy-violations",
                    "destruction-damage-vandalism-of-property",
                    "driving-under-the-influence",
                    "drug-equipment-violations", # GIVE SAME RESULTS AS NARCOTIC OFFENSES
                    "drug-violations", # GIVES EQUIPMENT VIOLATIONS RESULT
                    "drugs-narcotic-offenses", # GIVE SAME RESULTS AS EQUIPMENT VIOLATIONS
                    "drunkenness",
                    "embezzlement",
                    "extortion-blackmail",
                    "false-pretenses-swindle-confidence-game",
                    "fondling",
                    "fraud-offenses",
                    "gambling-equipment-violation",
                    "gambling-offenses",
                    "hacking-computer-invasion",
                    "homicide-offenses",
                    "human-trafficking-commerical-involuntary-servitude",
                    "human-trafficking-commerical-sex-acts",
                    "human-trafficking-offenses",
                    "identity-theft",
                    "impersonation",
                    "incest",
                    "intimidation",
                    "justifiable-homicide",
                    "kidnapping-abduction",
                    "larceny-theft-offenses",
                    "liquor-law-violations",
                    "motor-vehicle-theft",
                    "murder-and-nonnegligent-manslaughter",
                    "negligent-manslaughter",
                  #  "not-specified",
                    "operating-promoting-assiting-gambling",
                    "peeping-tom,pocket-picking",
                    "pornography-obscence-material",
                    "prostitution",
                    "prostitution-offenses",
                    "purchasing-prostitution",
                    "purse-snatching",
                    "rape",
                    "robbery",
                    "sex-offenses",
                    "sex-offenses-non-forcible",
                    "sexual-assult-with-an-object",
                    "shoplifting",
                    "simple-assault",
                    "sodomy",
                    "sports-tampering",
                    "statutory-rape",
                    "stolen-property-offenses",
                    "theft-from-building",
                    "theft-from-coin-operated-machine-or-device",
                    "theft-from-motor-vehicle",
                    "theft-of-motor-vehicle-parts-or-accessories",
                    "weapon-law-violation",
                    "welfare-fraud",
                    "wire-fraud")


nibrs_offender_variable <- c("age",
                             "count",
                             "ethnicity",
                             "race",
                             "sex")

nibrs_victim_variable <- c(nibrs_offender_variable, "relationship")

region_names <- c("U.S. Territories",
                  "Northeast",
                  "Midwest",
                  "South",
                  "West",
                  "Other")
