ucr_crime_categories <- c("",
                          "aggravated-assault",
                          "burglary",
                          "larceny",
                          "motor-vehicle-theft",
                          "homicide",
                          "rape",
                          "robbery",
                          "arson",
                          "violent-crime",
                          "property-crime")

ucr_arrest_offenses <- c("aggravated-assault",
                           "all-other-offenses",
                           "arson",
                           "burglary",
                           "curfew",
                           "disorderly-conduct",
                           "dui",
                           "drug-grand-total",
                           "drug-possession-marijuana",
                           "drug-possession-opium",
                           "drug-possession-other",
                           "drug-possession-subtotal",
                           "drug-possession-synthetic",
                           "drug-sales-marijuana",
                           "drug-sales-opium",
                           "drug-sales-other",
                           "drug-sales-subtotal",
                           "drug-sales-synthetic",
                           "drunkenness",
                           "embezzlement",
                           "forgery",
                           "fraud",
                           "gambling-all-other",
                           "gambling-bookmaking",
                           "gambling-numbers",
                           "gambling-total",
                           "human-trafficking-commercial",
                           "human-trafficking-servitude",
                           "larceny",
                           "liqour-laws", # MISPELLED
                           "motor-vehcile-theft", # MISPELLED
                           "murder",
                           "offense-against-family",
                           "prostitution",
                           "prostitution-assisting",
                           "prostitution-prostitution",
                           "prostitution-purchasing",
                           "rape",
                           "robbery",
                           "runaway",
                           "sex-offenses",
                           "simple-assault",
                           "stolen-property",
                           "suspicion",
                           "vagrancy",
                           "vandalism",
                           "weapons")

ucr_arrest_offense_categories <- c("violent_crime",
                                   "property_crime",
                                   "drug",
                                   "human_trafficking",
                                   "gambling",
                                   "juvenile",
                                   "society",
                                   "all")

ucr_arrest_types <- c("male",
                      "female",
                      "offense",
                      "race",
                      "monthly")

nibrs_offender_variable <- c("age",
                                    "count",
                                    "ethnicity",
                                    "race",
                                    "sex")
nibrs_victim_variable <- c(nibrs_offender_variable, "relationship")
